begin
  require 'bundler/setup'
rescue LoadError
  puts 'You must `gem install bundler` and `bundle install` to run rake tasks'
end

require 'rdoc/task'

RDoc::Task.new(:rdoc) do |rdoc|
  rdoc.rdoc_dir = 'rdoc'
  rdoc.title    = 'Core'
  rdoc.options << '--line-numbers'
  rdoc.rdoc_files.include('README.rdoc')
  rdoc.rdoc_files.include('lib/**/*.rb')
end



load 'rails/tasks/statistics.rake'

# load "haml-rails" raketask 
haml_rails = Gem::Specification.find_by_name "haml-rails"
load "#{haml_rails.gem_dir}/lib/tasks/erb2haml.rake"



Bundler::GemHelper.install_tasks

